package com.pomela.orm.mybatis.generator.model;

import java.math.BigDecimal;
import java.util.Date;

public class PayTransferRecord {
    /**
     * 主键id,所属表字段为pay_transfer_record.id
     */
    private Long id;

    /**
     * 接入方标识,所属表字段为pay_transfer_record.partner
     */
    private Byte partner;

    /**
     * 接入方唯一批次号,所属表字段为pay_transfer_record.out_batch_no
     */
    private String out_batch_no;

    /**
     * 内部唯一批次号,所属表字段为pay_transfer_record.batch_no
     */
    private String batch_no;

    /**
     * 支付工具,所属表字段为pay_transfer_record.pay_method_tool
     */
    private Byte pay_method_tool;

    /**
     * 支付工具平台id,所属表字段为pay_transfer_record.platform_id
     */
    private String platform_id;

    /**
     * 转入帐号，资金需要传入的帐号全名（包含域名）,必须为URS帐号,所属表字段为pay_transfer_record.account_in
     */
    private String account_in;

    /**
     * 转出账号,平台对应钱包帐号全名（转出帐号）,由网易宝指定或者由产品注册URS帐号后告诉支付组,所属表字段为pay_transfer_record.account_out
     */
    private String account_out;

    /**
     * 转账金额,所属表字段为pay_transfer_record.amount
     */
    private BigDecimal amount;

    /**
     * 任务状态：0开始 1成功 9失败,所属表字段为pay_transfer_record.state
     */
    private Byte state;

    /**
     * 转账时间,所属表字段为pay_transfer_record.transfer_time
     */
    private Long transfer_time;

    /**
     * 转账备注,所属表字段为pay_transfer_record.note
     */
    private String note;

    /**
     * 更新时间,所属表字段为pay_transfer_record.db_update_time
     */
    private Date db_update_time;

    /**
     * 创建时间,所属表字段为pay_transfer_record.db_create_time
     */
    private Date db_create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.id
     *
     * @return the value of pay_transfer_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.id
     *
     * @param id the value for pay_transfer_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.partner
     *
     * @return the value of pay_transfer_record.partner
     *
     * @mbggenerated
     */
    public Byte getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.partner
     *
     * @param partner the value for pay_transfer_record.partner
     *
     * @mbggenerated
     */
    public void setPartner(Byte partner) {
        this.partner = partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.out_batch_no
     *
     * @return the value of pay_transfer_record.out_batch_no
     *
     * @mbggenerated
     */
    public String getOut_batch_no() {
        return out_batch_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.out_batch_no
     *
     * @param out_batch_no the value for pay_transfer_record.out_batch_no
     *
     * @mbggenerated
     */
    public void setOut_batch_no(String out_batch_no) {
        this.out_batch_no = out_batch_no == null ? null : out_batch_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.batch_no
     *
     * @return the value of pay_transfer_record.batch_no
     *
     * @mbggenerated
     */
    public String getBatch_no() {
        return batch_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.batch_no
     *
     * @param batch_no the value for pay_transfer_record.batch_no
     *
     * @mbggenerated
     */
    public void setBatch_no(String batch_no) {
        this.batch_no = batch_no == null ? null : batch_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.pay_method_tool
     *
     * @return the value of pay_transfer_record.pay_method_tool
     *
     * @mbggenerated
     */
    public Byte getPay_method_tool() {
        return pay_method_tool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.pay_method_tool
     *
     * @param pay_method_tool the value for pay_transfer_record.pay_method_tool
     *
     * @mbggenerated
     */
    public void setPay_method_tool(Byte pay_method_tool) {
        this.pay_method_tool = pay_method_tool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.platform_id
     *
     * @return the value of pay_transfer_record.platform_id
     *
     * @mbggenerated
     */
    public String getPlatform_id() {
        return platform_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.platform_id
     *
     * @param platform_id the value for pay_transfer_record.platform_id
     *
     * @mbggenerated
     */
    public void setPlatform_id(String platform_id) {
        this.platform_id = platform_id == null ? null : platform_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.account_in
     *
     * @return the value of pay_transfer_record.account_in
     *
     * @mbggenerated
     */
    public String getAccount_in() {
        return account_in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.account_in
     *
     * @param account_in the value for pay_transfer_record.account_in
     *
     * @mbggenerated
     */
    public void setAccount_in(String account_in) {
        this.account_in = account_in == null ? null : account_in.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.account_out
     *
     * @return the value of pay_transfer_record.account_out
     *
     * @mbggenerated
     */
    public String getAccount_out() {
        return account_out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.account_out
     *
     * @param account_out the value for pay_transfer_record.account_out
     *
     * @mbggenerated
     */
    public void setAccount_out(String account_out) {
        this.account_out = account_out == null ? null : account_out.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.amount
     *
     * @return the value of pay_transfer_record.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.amount
     *
     * @param amount the value for pay_transfer_record.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.state
     *
     * @return the value of pay_transfer_record.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.state
     *
     * @param state the value for pay_transfer_record.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.transfer_time
     *
     * @return the value of pay_transfer_record.transfer_time
     *
     * @mbggenerated
     */
    public Long getTransfer_time() {
        return transfer_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.transfer_time
     *
     * @param transfer_time the value for pay_transfer_record.transfer_time
     *
     * @mbggenerated
     */
    public void setTransfer_time(Long transfer_time) {
        this.transfer_time = transfer_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.note
     *
     * @return the value of pay_transfer_record.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.note
     *
     * @param note the value for pay_transfer_record.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.db_update_time
     *
     * @return the value of pay_transfer_record.db_update_time
     *
     * @mbggenerated
     */
    public Date getDb_update_time() {
        return db_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.db_update_time
     *
     * @param db_update_time the value for pay_transfer_record.db_update_time
     *
     * @mbggenerated
     */
    public void setDb_update_time(Date db_update_time) {
        this.db_update_time = db_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_transfer_record.db_create_time
     *
     * @return the value of pay_transfer_record.db_create_time
     *
     * @mbggenerated
     */
    public Date getDb_create_time() {
        return db_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_transfer_record.db_create_time
     *
     * @param db_create_time the value for pay_transfer_record.db_create_time
     *
     * @mbggenerated
     */
    public void setDb_create_time(Date db_create_time) {
        this.db_create_time = db_create_time;
    }
}