package com.pomela.orm.mybatis.generator.dao;

import com.pomela.orm.mybatis.generator.model.GoodsInfoSnapshot;

public interface GoodsInfoSnapshotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info_snapshot
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info_snapshot
     *
     * @mbggenerated
     */
    int insert(GoodsInfoSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info_snapshot
     *
     * @mbggenerated
     */
    int insertSelective(GoodsInfoSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info_snapshot
     *
     * @mbggenerated
     */
    GoodsInfoSnapshot selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info_snapshot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsInfoSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info_snapshot
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsInfoSnapshot record);
}