package com.pomela.orm.mybatis.generator.dao;

import com.pomela.orm.mybatis.generator.model.LogisticInfo;

public interface LogisticInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistic_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistic_info
     *
     * @mbggenerated
     */
    int insert(LogisticInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistic_info
     *
     * @mbggenerated
     */
    int insertSelective(LogisticInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistic_info
     *
     * @mbggenerated
     */
    LogisticInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistic_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogisticInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistic_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogisticInfo record);
}